version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hospital-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Subbu949166@
      MYSQL_DATABASE: hospital-application
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hospital-network

volumes:
  mysql_data:

networks:
  hospital-network:
